---

reference_time: 2021-11-06 00:00

default_stream:
  type: ticker
  product_ids:
    - BTC-USD
  channels:
    - ticker
    - user

# path to yaml containing definitions for API keys; example below
# (this will be handled more securely in the future)
#
# key_nickname:
#   public: access_key_string
#   private: secret_key_string
#   passphrase: user_passphrase_string
#    
keys_file: C:\Users\Me\Documents\python\cbkeys.neutrino-private

# cbpro websocket feed endpoint URL
stream_url: wss://ws-feed.pro.coinbase.com

# cbpro API URL
api_url: https://api.pro.coinbase.com

# test file with other sensitive info
test_parameters_file: C:\Users\Me\Documents\python\test_parameters.neutrino-private