---

# cbpro websocket feed endpoint URL
stream_url: wss://ws-feed.pro.coinbase.com

# cbpro API URL
api_url: https://api.pro.coinbase.com

# cbpro API response keys
api_response_keys:
  accounts: currency
  ledger: id
  transfers: id
  orders: id

# update info
pip_install: True
changelog:
  - Placeholder text for a summary of changes incorporated in this update.
  - This changelog is in the form a list.
  - The list contains an arbitrary number of elements.