---

# cbpro websocket feed endpoint URL
stream_url: wss://ws-feed.pro.coinbase.com

# cbpro API URL
api_url: https://api.pro.coinbase.com

# update info
pip_install: True
changelog:
  - placeholder 1
  - placeholder 2